alter session set deferred_segment_creation=false;

DROP TABLE MEMBER;
DROP TABLE EMPLOYEE;
DROP TABLE PERMISSION;
DROP TABLE DEPOSITDETAIL;
DROP TABLE EMPPERMISSIONDETAIL;
DROP TABLE CUSTOMESERVICERECORD;
DROP TABLE ADVERTISEMENT;
DROP TABLE INFORMATION ;

DROP SEQUENCE MEMBER_seq;
DROP SEQUENCE EMPLOYEE_seq;
DROP SEQUENCE PERMISSION_seq;
DROP SEQUENCE DEPOSITDETAIL_seq;
DROP SEQUENCE EMPPERMISSIONDETAIL_seq;
DROP SEQUENCE CUSTOMESERVICERECORD_seq;
DROP SEQUENCE ADVERTISEMENT_seq;
DROP SEQUENCE INFORMATION_seq;

----------------------------------------------------------
--建立會員表格
 
CREATE TABLE MEMBER(
MEMBER_NO    		VARCHAR2(20)   PRIMARY KEY NOT NULL,
MEMBER_ACCOUNT  	VARCHAR2(20)   NOT NULL,
MEMBER_PASSWORD 	VARCHAR2(100)  NOT NULL,
MEMBER_NAME  		VARCHAR2(20)   NOT NULL,
MEMBER_NICK			VARCHAR2(20),
MEMBER_SEX			NUMBER(1)	   NOT NULL,
MEMBER_BIRTHDAY		DATE	   	   NOT NULL,
MEMBER_ADDRESS		VARCHAR2(100)  NOT NULL,	
MEMBER_EMAIL		VARCHAR2(100)  NOT NULL,	
MEMBER_PICTURE		BLOB,	
MEMBER_BUILDDAY		DATE	       NOT NULL,
MEMBER_POINT		NUMBER(10)	   NOT NULL,
MEMBER_STATUS		VARCHAR2(20)   NOT NULL
);



CREATE SEQUENCE MEMBER_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;



INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'A123456','123456','DAVID','POKENMONMASTER',1,TO_DATE('1981-11-17','YYYY-MM-DD'),'台北市天母區天龍路1號','pokoman1314520@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 500,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'B123456','12345','PETER','WU-GOD',1,TO_DATE('1971-01-08','YYYY-MM-DD'),'台北市中正區大神路1號','123JAVAsoeasy@gmail.com',null , TO_DATE('2019-02-02','YYYY-MM-DD'), 1500,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'C123456','Z123456','AGEA','AEN',0,TO_DATE('2000-03-05','YYYY-MM-DD'),'新北市中正區路1號','s1022546@gmail.com',null , TO_DATE('2019-02-01','YYYY-MM-DD'), 5500,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'D123456','a23456','BOBO','BO',1,TO_DATE('2005-04-28','YYYY-MM-DD'),'桃園市中壢區中央路1號','a7513323@gmail.com',null , TO_DATE('2019-01-03','YYYY-MM-DD'), 2500,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'E123456','b12456','CICI','GAY',1,TO_DATE('1977-05-06','YYYY-MM-DD'),'新竹縣湖口鄉湖口路1號','s78423@gmail.com',null , TO_DATE('2019-01-13','YYYY-MM-DD'), 100,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'F123456','c23456','DOG','NOGIRLFRIEND',1,TO_DATE('1981-10-17','YYYY-MM-DD'),'苗栗市草莓區樂桃路1號','d89896@gmail.com',null , TO_DATE('2019-01-20','YYYY-MM-DD'), 50,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'G123456','d23456','SOPIYA','LONG',0,TO_DATE('2000-10-10','YYYY-MM-DD'),'台中市霧峰區中央路1號','f00000@gmail.com',null , TO_DATE('2019-01-01','YYYY-MM-DD'), 700,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'H123456','e23456','GAGA','LADY',0,TO_DATE('1994-05-23','YYYY-MM-DD'),'彰化縣彰化市精誠路1號','g7897798@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 600,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'I123456','f23456','WANG','WANG40',1,TO_DATE('1997-03-27','YYYY-MM-DD'),'雲林縣雲林市虎尾路1號','q026554564@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 400,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'J123456','g23456','CHEN','C',1,TO_DATE('1988-11-20','YYYY-MM-DD'),'嘉義市火雞路1號','avc78789@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 200,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'K123456','h23456','JIA','JIAJIA',0,TO_DATE('1959-01-01','YYYY-MM-DD'),'台南市赤崁區中央路1號','fff48798@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 1500,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'L123456','h23456','WILLIAM','WIN',0,TO_DATE('1999-07-22','YYYY-MM-DD'),'高雄市鳳山區韓流路1號','gggg7879@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 1000,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'N123456','j23456','PEN','PP',1,TO_DATE('1989-10-23','YYYY-MM-DD'),'花蓮縣花蓮市中央路1號','fdsf5466@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 3000,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'O123456','u23456','ANDY','NICO',1,TO_DATE('1995-08-07','YYYY-MM-DD'),'台東縣知本鄉溫泉路1號','NICO520@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 4000,0);
INSERT INTO MEMBER VALUES (MEMBER_seq.NEXTVAL , 'P123456','i23456','NICO','LOVE',0,TO_DATE('1995-06-09','YYYY-MM-DD'),'台東縣綠島鄉海岸路1號','ANDY520@gmail.com',null , TO_DATE('2019-02-03','YYYY-MM-DD'), 5000,0);

----------------------------------------------------------
--建立員工表格 

CREATE TABLE EMPLOYEE(

EMPLOYEE_NO			VARCHAR2(20)	PRIMARY KEY NOT NULL,
EMPLOYEE_NAME		VARCHAR2(20)	NOT NULL,
EMPLOYEE_SEX		NUMBER(1)		NOT NULL,
EMPLOYEE_BUILDDATE	DATE			NOT NULL,
EMPLOYEE_QUITDATE	DATE,		
EMPLOYEE_ABILITY	VARCHAR2(20),		
EMPLOYEE_STATUS		VARCHAR2(20)	NOT NULL

);


CREATE  SEQUENCE EMPLOYEE_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'DAVID',1,TO_DATE('2018-01-10','YYYY-MM-DD'),null,'文書',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'PETER',1,TO_DATE('2014-02-11','YYYY-MM-DD'),null,'文書',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'BRAIN',1,TO_DATE('2017-03-12','YYYY-MM-DD'),TO_DATE('2019-02-04','YYYY-MM-DD'),'日文',0);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Terrance',1,TO_DATE('2010-04-13','YYYY-MM-DD'),null,'英文',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Madison',1,TO_DATE('2019-05-14','YYYY-MM-DD'),null,'韓文',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Kayleigh',0,TO_DATE('2017-06-15','YYYY-MM-DD'),null,'會計',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Danielle',0,TO_DATE('2016-07-16','YYYY-MM-DD'),null,'財金',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Katie',0,TO_DATE('2013-08-17','YYYY-MM-DD'),TO_DATE('2019-02-04','YYYY-MM-DD'),'文書',0);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Ashley',0,TO_DATE('2011-09-18','YYYY-MM-DD'),null,'行銷',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Marquis',1,TO_DATE('2015-10-19','YYYY-MM-DD'),null,'人事',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Marisa',0,TO_DATE('2016-11-20','YYYY-MM-DD'),null,'文書',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Cynthia',0,TO_DATE('2017-12-23','YYYY-MM-DD'),null,'文書',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Alex',1,TO_DATE('2018-01-24','YYYY-MM-DD'),null,'資訊',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Caroline',0,TO_DATE('2019-02-26','YYYY-MM-DD'),null,'資訊',1);
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_seq.NEXTVAL ,'Abigayle',0,TO_DATE('2014-03-29','YYYY-MM-DD'),null,'總務',1);


-----------------------------------------------------------
--建立權限表格

CREATE TABLE PERMISSION(

PERMISSION_NO		VARCHAR2(20)		PRIMARY KEY NOT NULL, 
PERMISSION_NAME		VARCHAR2(20)		NOT NULL

);


CREATE SEQUENCE PERMISSION_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'停權管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'訂票紀錄調閱' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'儲值紀錄調閱' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'揪團紀錄調閱' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'檢舉處理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'活動優惠管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'一般票價管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'影廳管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'上映管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'電影資訊管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'年度排行管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'新聞管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'作家影評管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'最新公告管理' );
INSERT INTO PERMISSION VALUES (PERMISSION_seq.NEXTVAL ,'廣告管理' );

-----------------------------------------------------------
--建立剩餘點數異動明細表格

CREATE TABLE DEPOSITDETAIL(

DEPOSIT_CHANGE_NO		VARCHAR2(20)	PRIMARY KEY NOT NULL,
DEPOSIT_MEMBER_NO		VARCHAR2(20)	NOT NULL,
DEPOSIT_CHANGE_MONEY	NUMBER(20)		NOT NULL,
DEPOSIT_CHANGE_DATE		DATE			NOT NULL

);


CREATE SEQUENCE DEPOSITDETAIL_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;



INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,200, TO_DATE('2019-01-03','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,300, TO_DATE('2019-01-04','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,400, TO_DATE('2019-01-05','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,500, TO_DATE('2019-01-06','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,600, TO_DATE('2019-01-07','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,700, TO_DATE('2019-01-08','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,800, TO_DATE('2019-01-09','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,1500, TO_DATE('2019-01-10','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,200, TO_DATE('2019-01-11','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,500, TO_DATE('2019-02-01','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,600, TO_DATE('2019-02-02','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,300, TO_DATE('2019-02-03','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,100, TO_DATE('2019-02-04','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,200, TO_DATE('2019-02-05','YYYY-MM-DD') );
INSERT INTO DEPOSITDETAIL VALUES (DEPOSITDETAIL_seq.NEXTVAL ,1,500, TO_DATE('2019-02-06','YYYY-MM-DD') );
----------------------------------------------------------
--建立員工權限明細表格

CREATE TABLE EMPPERMISSIONDETAIL(

EMPLOYEE_NO		VARCHAR2(20)		 NOT NULL,
PERMISSION_NO	VARCHAR2(20)		 NOT NULL,

CONSTRAINT PK_EMPPERMISSIONDETAIL    PRIMARY KEY (EMPLOYEE_NO,PERMISSION_NO)

);



CREATE SEQUENCE EMPPERMISSIONDETAIL_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;



INSERT INTO EMPPERMISSIONDETAIL VALUES (1 ,1);
INSERT INTO EMPPERMISSIONDETAIL VALUES (2 ,2);
INSERT INTO EMPPERMISSIONDETAIL VALUES (3 ,3);
INSERT INTO EMPPERMISSIONDETAIL VALUES (4 ,4);
INSERT INTO EMPPERMISSIONDETAIL VALUES (5 ,5);
INSERT INTO EMPPERMISSIONDETAIL VALUES (6 ,6);
INSERT INTO EMPPERMISSIONDETAIL VALUES (7 ,7);
INSERT INTO EMPPERMISSIONDETAIL VALUES (8 ,8);
INSERT INTO EMPPERMISSIONDETAIL VALUES (9 ,9);
INSERT INTO EMPPERMISSIONDETAIL VALUES (10 ,10);
INSERT INTO EMPPERMISSIONDETAIL VALUES (11,11);
INSERT INTO EMPPERMISSIONDETAIL VALUES (12,12);
INSERT INTO EMPPERMISSIONDETAIL VALUES (13,13);
INSERT INTO EMPPERMISSIONDETAIL VALUES (14,14);
INSERT INTO EMPPERMISSIONDETAIL VALUES (15,15);
-----------------------------------------------------------
--建立客服紀錄表格

CREATE TABLE CUSTOMESERVICERECORD(
 
CUSTOMER_SERVICE_EVENT_NO			VARCHAR2(20)		PRIMARY KEY NOT NULL,
MEMBER_NO							VARCHAR2(20)		NOT NULL,
CUSTOMER_SERVICE_START_DATE	DATE						NOT NULL,
CUSTOMER_SERVICE_STATUS				VARCHAR2(20)		NOT NULL

);



CREATE SEQUENCE CUSTOMESERVICERECORD_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 1 ,TO_DATE('2019-01-01','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 2 ,TO_DATE('2019-01-02','YYYY-MM-DD'),0);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 3 ,TO_DATE('2019-01-03','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 4 ,TO_DATE('2019-01-04','YYYY-MM-DD'),0);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 5 ,TO_DATE('2019-01-05','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 6 ,TO_DATE('2019-01-06','YYYY-MM-DD'),0);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 7 ,TO_DATE('2019-01-07','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 8 ,TO_DATE('2019-01-08','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 9 ,TO_DATE('2019-01-09','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 10,TO_DATE('2019-02-01','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 11,TO_DATE('2019-02-02','YYYY-MM-DD'),0);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 12,TO_DATE('2019-02-03','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 13,TO_DATE('2019-02-04','YYYY-MM-DD'),1);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 14,TO_DATE('2019-02-05','YYYY-MM-DD'),0);
INSERT INTO CUSTOMESERVICERECORD VALUES (CUSTOMESERVICERECORD_seq.NEXTVAL , 15,TO_DATE('2019-02-06','YYYY-MM-DD'),1);
-----------------------------------------------------------
--建立廣告表格

CREATE TABLE ADVERTISEMENT(

AD_NO		VARCHAR2(20)		PRIMARY KEY NOT NULL,
AD_NAME		VARCHAR2(20)		NOT NULL,
AD_PIC		BLOB,
AD_CONT		VARCHAR2(200)		NOT NULL,
AD_START	DATE				NOT NULL,
AD_END		DATE		

);


CREATE SEQUENCE ADVERTISEMENT_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'聖誕',null,100,TO_DATE('2018-12-01','YYYY-MM-DD'),TO_DATE('2018-12-26','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'聖誕',null,100,TO_DATE('2018-12-20','YYYY-MM-DD'),TO_DATE('2018-12-26','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'跨年',null,300,TO_DATE('2018-12-30','YYYY-MM-DD'),TO_DATE('2019-01-02','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'元旦',null,400,TO_DATE('2019-01-01','YYYY-MM-DD'),TO_DATE('2019-01-02','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'新年',null,500,TO_DATE('2019-01-31','YYYY-MM-DD'),TO_DATE('2019-02-10','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'新年',null,600,TO_DATE('2019-02-01','YYYY-MM-DD'),TO_DATE('2019-02-10','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'新年',null,700,TO_DATE('2019-02-02','YYYY-MM-DD'),TO_DATE('2019-02-10','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'新年',null,800,TO_DATE('2019-01-10','YYYY-MM-DD'),TO_DATE('2019-02-14','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'情人節',null,900,TO_DATE('2019-02-12','YYYY-MM-DD'),TO_DATE('2019-02-14','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'情人節',null,1000,TO_DATE('2019-02-13','YYYY-MM-DD'),TO_DATE('2019-02-14','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'情人節',null,1100,TO_DATE('2019-02-14','YYYY-MM-DD'),TO_DATE('2019-03-03','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'白色情人',null,1200,TO_DATE('2019-03-13','YYYY-MM-DD'),TO_DATE('2019-03-14','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'白色情人',null,1300,TO_DATE('2019-03-14','YYYY-MM-DD'),TO_DATE('2019-03-14','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'端午',null,1400,TO_DATE('2019-05-05','YYYY-MM-DD'),TO_DATE('2019-05-10','YYYY-MM-DD') );
INSERT INTO ADVERTISEMENT VALUES (ADVERTISEMENT_seq.NEXTVAL ,'端午',null,1500,TO_DATE('2019-05-06','YYYY-MM-DD'),TO_DATE('2019-05-10','YYYY-MM-DD') );
---------------------------------------------------------
--建立公告資料欄位

CREATE TABLE INFORMATION(
INFO_NO			VARCHAR2(20)		PRIMARY KEY NOT NULL,
INFO_CONTENT	VARCHAR2(200)		NOT NULL,
INFO_DESC		VARCHAR2(200)		NOT NULL,
INFO_DATE		DATE				NOT NULL

);



CREATE SEQUENCE INFORMATION_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '聖誕優惠','優惠快來好棒棒 ',TO_DATE('2018-12-01','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '聖誕優惠','優惠快來好棒棒 ',TO_DATE('2018-12-20','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '跨年優惠','優惠快來好棒棒 ',TO_DATE('2018-12-30','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '元旦優惠','優惠快來好棒棒 ',TO_DATE('2019-01-01','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '新年優惠','優惠快來好棒棒 ',TO_DATE('2019-01-31','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '新年優惠','優惠快來好棒棒 ',TO_DATE('2019-02-01','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '新年優惠','優惠快來好棒棒 ',TO_DATE('2019-02-02','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '新年優惠','優惠快來好棒棒 ',TO_DATE('2019-01-10','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '情人節優惠','優惠快來好棒棒 ',TO_DATE('2019-02-12','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '情人節優惠','優惠快來好棒棒 ',TO_DATE('2019-02-13','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '情人節優惠','優惠快來好棒棒 ',TO_DATE('2019-02-14','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '白色優惠','優惠快來好棒棒 ',TO_DATE('2019-03-13','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '白色優惠','優惠快來好棒棒 ',TO_DATE('2019-03-14','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '端午優惠','優惠快來好棒棒 ',TO_DATE('2019-05-05','YYYY-MM-DD'));
INSERT INTO INFORMATION VALUES (INFORMATION_seq.NEXTVAL , '端午優惠','優惠快來好棒棒 ',TO_DATE('2019-05-06','YYYY-MM-DD'));

commit;



